name = "DirectQuadratureZero"
uuid = "65333657-a398-4ec2-b6f8-0db2ba707f75"
authors = ["Blanca_Luo"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
